fail_fast: true
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.47.2
    hooks:
      - id: golangci-lint
